### ISSUE TITLE
Exception after Updating XCode and Simulators to iOS 13

### ISSUE THREAD

**Issue by sceee** [mmcc007/screenshots#137] opened 2019-10-03 19:13 UTC
I am experiencing the following exception when trying to execute `screenshots`.
It feels as this is now happening after XCode and the simulator have been updated to iOS 13 but I can't definitely confirm that that's the reason. It worked previously, though.

This is the exception I am getting:
```
Unhandled exception:
command failed: exitcode=1, cmd='plutil -convert json -o - /Users/XX/Library/Developer/CoreSimulator/Devices/45985FB6-6B62-4436-9B08-D33838C3BC85/data/Library/Preferences/.GlobalPreferences.plist', workingDir=.
#0      cmd (package:screenshots/src/utils.dart:360:5)
#1      getIosSimulatorLocale (package:screenshots/src/utils.dart:178:19)
#2      runTestsOnAll (package:screenshots/src/run.dart:223:38)
<asynchronous suspension>
#3      runScreenshots (package:screenshots/src/run.dart:109:9)
<asynchronous suspension>
#4      screenshots.<anonymous closure> (package:screenshots/src/run.dart:45:14)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:153:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:tool_base/src/base/context.dart:152:18)
<asynchronous suspension>
#11     runInContext (package:screenshots/src/context_runner.dart:16:24)
<asynchronous suspension>
#12     screenshots (package:screenshots/src/run.dart:44:12)
<asynchronous suspension>
#13     main 

```

If I execute `plutil -convert json -o - /Users/XX/Library/Developer/CoreSimulator/Devices/45985FB6-6B62-4436-9B08-D33838C3BC85/data/Library/Preferences/.GlobalPreferences.plist` I get a file not found error.

**Comment by AndreyMatos** [comment] 2019-10-04 14:59
I think you have to open the simulator at least once after updating xcode.
That worked for me.

**Comment by sceee** [comment] 2019-10-04 18:25
@AndreyMatos thank you very much, that did the trick.

Make sure every simulator you need is installed and at least once started after the XCode update.

**Comment by mcrovero** [comment] 2019-11-26 10:44
Still getting this error, cannot use the library on CI

**Comment by mmcc007** [comment] 2019-11-26 13:40
Not encountering this issue when running on travis with xcode 11.2 (macOS 10.14) (see [travis build](https://travis-ci.com/mmcc007/screenshots/jobs/259830197)). If running on a different CI perhaps starting and shutting-down the simulators in advance as suggested above might help.

First inspect the installed device types and runtimes with
```
xcrun simctl list devicetypes
xcrun simctl list runtimes
```
Select the most recent runtime (screenshots defaults to the most recent runtime).

Then start/stop a simulator with something like
```
# create simulator
udid=$(xcrun simctl create "iPhone X" com.apple.CoreSimulator.SimDeviceType.iPhone-X com.apple.CoreSimulator.SimRuntime.iOS-13-2)
# boot simulator
xcrun simctl boot $udid
# shutdown simulator
xcrun simctl shutdown $udid
```

Let me know if this helps.

**Comment by mcrovero** [comment] 2019-11-26 14:22
I've tried with github actions and now I'm experiencing the same on codemagic.
In both environments, I've tested your suggestion of creating, booting and shutting down the emulator but the error persists. 
I'm using the version 2.1.1 but on travis and cirrus you're using the unreleased version which is some commits ahead.. can it be the cause of the error?

Thanks in advance for the quick support

**Comment by mmcc007** [comment] 2019-11-26 20:36
@mcrovero Was able to recreate this on [travis](https://travis-ci.com/mmcc007/screenshots/jobs/260662343#L2286).

Have a fix for this by creating the .GlobalPreferences.plist if missing (https://github.com/mmcc007/screenshots/commit/6a5f88b86d0a4427c05c3b3c64f8239fcc89ff07). Looks like it is working on multiple CIs ([cirrus](https://cirrus-ci.com/task/5913079539302400), [travis](https://travis-ci.com/mmcc007/screenshots/jobs/260734541)).

You can try it out in your CI:
```
git clone https://github.com/mmcc007/screenshots
git checkout 106_ios_13
pub global activate --source path .
```

Let me know how it goes.

**Closed** 2019-11-27 02:04 UTC
Labels: question

**Comment by mmcc007** [comment] 2019-11-27 02:05
The merge should resolve the issue. If not, please re-open.

**Comment by mcrovero** [comment] 2019-11-27 16:34
I can confirm it has been solved! 
Thanks  🎉
