### ISSUE TITLE
example project not working either

### ISSUE THREAD

**Issue by Xgamefactory** [mmcc007/screenshots#160] opened 2019-11-22 15:37 UTC
<img width="917" alt="Screen Shot 2019-11-22 at 19 35 46" src="https://user-images.githubusercontent.com/22529051/69438954-6d001e80-0d5f-11ea-8d6a-670fecb2654f.png">

```
No device attached or emulator installed for device 'Nexus 6P' in screenshots.yaml.
No device attached or simulator installed for device 'iPhone XS Max' in screenshots.yaml.

Guide:

  Attached devices:
    SM G965F

  Installed emulators:
    10.1_WXGA_Tablet_API_29
    Nexus_5X_API_29_x86
    Nexus_7_API_29

  Installed simulators:
    Apple TV
    Apple TV 4K
    Apple TV 4K (at 1080p)
    Apple Watch Series 4 - 40mm
    Apple Watch Series 4 - 44mm
    Apple Watch Series 5 - 40mm
    Apple Watch Series 5 - 44mm
    iPhone 11
    iPhone 11 Pro
    iPhone 11 Pro Max
    iPhone 8
    iPhone 8 Plus
    iPad (7th generation)
    iPad Air (3rd generation)
    iPad Pro (11-inch)
    iPad Pro (12.9-inch) (3rd generation)
    iPad Pro (9.7-inch)

  Supported screens:
    android:
      Nexus 5X
      Nexus 6P
      Nexus 9
    ios:
      iPhone 6 Plus
      iPhone 6S Plus
      iPhone 6s Plus
      iPhone 7 Plus
      iPhone 8 Plus
      iPhone X
      iPhone XS
      iPhone XS Max
      iPhone Xs
      iPhone Xs Max
      iPad Pro (12.9-inch) (1st generation)
      iPad Pro (12.9-inch) (2nd generation)
      iPad Pro (12.9-inch) (3rd generation)

  Each device listed in screenshots.yaml with framing required must
    1. have a supported screen
    2. have an attached device or an installed emulator/simulator.
  To bypass requirement #1 add 'frame: false' after device in screenshots.yaml
```

**Comment by mmcc007** [comment] 2019-11-22 21:07
I just ran
```
screenshots -c screenshots_ios.yaml
```
on the example app and it ran normally.
It may be related to the version of Xcode you are running. I am running on `Xcode 10.1, Build version 10B61`.

Also, in the past, there has been some in consistency in what the command
```
xcrun simctl list devices --json
```
returns for different locales and versions of Xcode. Can you give me your output?

**Comment by Xgamefactory** [comment] 2019-11-23 16:57
Thanks for response. we got same error with command

> screenshots -c screenshots_ios.yaml

Here is the output of 

```
$ xcrun simctl list devices --json
{
  "devices" : {
    "com.apple.CoreSimulator.SimRuntime.watchOS-5-3" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 2 - 38mm",
        "udid" : "5A9407BA-5C22-481A-8F02-000266EE2CD6",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 2 - 42mm",
        "udid" : "7C82D891-F1BC-4E5B-A375-43423AC1FE57",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 3 - 38mm",
        "udid" : "6D1CD041-B1B1-4845-B07D-4AFF88866EF4",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 3 - 42mm",
        "udid" : "1879985E-88A3-405A-AAAF-070114228D21",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 4 - 40mm",
        "udid" : "B6A13BF4-C7BD-4ECA-A700-F723B11DF06F",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 4 - 44mm",
        "udid" : "C098C967-9030-4305-A70E-E26BFB814CAC",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.watchOS-6-0" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 4 - 40mm",
        "udid" : "4E75BCE3-BA90-483F-8F2A-EA5734840B5F",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 4 - 44mm",
        "udid" : "607C6F26-78BC-4CEB-AA0E-7FD0EC98A4F6",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 5 - 40mm",
        "udid" : "32691C5C-F66C-46C3-BF26-B890224C4AF8",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple Watch Series 5 - 44mm",
        "udid" : "EFE1794C-0158-4145-A816-C665CE260E23",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.tvOS-13-0" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV",
        "udid" : "4FD1B69A-C3AE-4F5F-BF82-554C132BE67B",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV 4K",
        "udid" : "186BA876-E070-47F9-A420-507F9C616D3E",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV 4K (at 1080p)",
        "udid" : "11819E7F-E6F5-41E3-A996-D22F9B1BA796",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-12-4" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 5s",
        "udid" : "091D537E-9945-45FB-8B34-DA4815318662",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 6 Plus",
        "udid" : "680F8498-3DBE-4E7B-831C-3256C8A222EA",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 6",
        "udid" : "1382EC4A-3D97-42C1-8576-FC5CED713348",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 6s",
        "udid" : "E5A68B3D-008D-4C4F-BA2D-220509CF8699",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 6s Plus",
        "udid" : "7ABA6640-CAE2-4D13-8AB6-B9E5AB8546CF",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone SE",
        "udid" : "C59F1BE9-5C46-4CEB-814D-DE26D95C8DA7",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 7",
        "udid" : "B45595E5-58E3-4115-B8DF-8FFD39B3AF2C",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 7 Plus",
        "udid" : "A9F2693C-39A0-4085-8E17-5537094FAC7D",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 8",
        "udid" : "9D0DB640-5BF2-46D5-BB3C-BC794BFC9AB5",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 8 Plus",
        "udid" : "F7179441-FE79-47CB-9BDC-D5B551CFB2D4",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone X",
        "udid" : "D02F754F-F2D5-4C42-8E6A-7944B02279D9",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone Xs",
        "udid" : "1EF2C5F6-E73C-44B3-8030-432D05DFD81F",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone Xs Max",
        "udid" : "A61B2298-7975-4A72-8D1B-94E36775B582",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone Xʀ",
        "udid" : "6F1119D6-D48A-42D9-BA9B-44A537336DDB",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Air",
        "udid" : "478468BA-2B8C-4ED4-8652-43FCCAE09F4B",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Air 2",
        "udid" : "9136AFAA-9446-426A-AEA9-CAF6B84EC4E5",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (9.7-inch)",
        "udid" : "445C98DE-3140-4948-8D7D-53D77DBE23F9",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (12.9-inch)",
        "udid" : "0145364A-C4BA-4696-956F-DDB1E9503F78",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad (5th generation)",
        "udid" : "D7AE2AFA-F51D-47EA-B16A-7AA2670054CE",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (12.9-inch) (2nd generation)",
        "udid" : "ABE29707-258A-4BCB-8848-16AEDF3C2C89",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (10.5-inch)",
        "udid" : "54F0455E-C1DE-4E95-BF92-5C901E06AFB9",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad (6th generation)",
        "udid" : "122C242F-A072-4E23-B7C1-048F3CDE4FEF",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (11-inch)",
        "udid" : "583F6085-C718-4E28-8808-06182D478503",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (12.9-inch) (3rd generation)",
        "udid" : "DADB0F01-E69D-4A30-808A-8993D24D9228",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Air (3rd generation)",
        "udid" : "FF4BB9F6-EE98-4C54-A381-E3D92196B0C0",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.tvOS-12-4" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV",
        "udid" : "A0C73976-F56F-4D86-98E5-5C618D2F2A50",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV 4K",
        "udid" : "9445BBEA-C1A9-4E6A-8A09-6404C9033FD9",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV 4K (at 1080p)",
        "udid" : "BE773A26-45B3-4C01-A5A3-BED2402791CD",
        "availabilityError" : "runtime profile not found"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.tvOS-13-2" : [
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple TV",
        "udid" : "026EA621-E451-4A6A-A0A7-03D2708A7511"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple TV 4K",
        "udid" : "3DAC9A3D-20F8-431F-8DC1-9DA79436091F"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple TV 4K (at 1080p)",
        "udid" : "EE4A05C5-82DB-45E2-8FBA-74E2EF514A9D"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.watchOS-6-1" : [
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 4 - 40mm",
        "udid" : "468FDF5B-93EE-4223-89CB-F1226763BA53"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 4 - 44mm",
        "udid" : "083DF8E6-965A-4025-BAF8-CD09ACABCD56"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 5 - 40mm",
        "udid" : "AC96F97B-072D-4C10-888C-8BA0570E46B3"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "Apple Watch Series 5 - 44mm",
        "udid" : "2120FFC2-72E9-423F-84FC-CD7C2AED7803"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-13-2" : [
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 8",
        "udid" : "5802D126-9CD1-4DDC-A658-3906DEC5EEC1"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 8 Plus",
        "udid" : "8276FBAA-A6C0-48BC-96AE-921E4D11E96E"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 11",
        "udid" : "F7AD3247-5FC1-493E-BF52-61C83D635F32"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 11 Pro",
        "udid" : "08649D45-7DBD-4C82-B40D-E6440EAD65DD"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 11 Pro Max",
        "udid" : "0E950AC8-525C-4C1F-A3E7-A7FD4A448C70"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (9.7-inch)",
        "udid" : "F3C660BD-D794-4DCC-BA27-BAA1311892E1"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad (7th generation)",
        "udid" : "4A3AAF9C-1D4F-4731-B02C-3DFFA463BAF1"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (11-inch)",
        "udid" : "095430F5-2E99-4FFE-AA26-75AFFA45DFB5"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Pro (12.9-inch) (3rd generation)",
        "udid" : "4BCF7116-8658-4FEA-8D60-B5361EB26DD7"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPad Air (3rd generation)",
        "udid" : "E55C0C08-E600-4D7C-ACBE-63941441A8D0"
      }
    ],
    "com.apple.CoreSimulator.SimRuntime.iOS-13-0" : [
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 8",
        "udid" : "6512BB73-37A7-469F-84E6-2DD9B976F7BE",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 8 Plus",
        "udid" : "C9D17586-86AD-4D0B-A46B-F89D46344785",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 11",
        "udid" : "03388716-B45E-41D5-BFB7-8181AE321D66",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 11 Pro",
        "udid" : "A7A16560-8EA5-49BB-B391-75EAFA3A6EEA",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPhone 11 Pro Max",
        "udid" : "EB822940-53F3-4AEB-9EF9-FBCE2F97FD46",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (9.7-inch)",
        "udid" : "EA581802-EE51-494F-A3C3-00414DF392AC",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (11-inch)",
        "udid" : "6A20AE57-960B-4923-81AD-4A6992682ED1",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Pro (12.9-inch) (3rd generation)",
        "udid" : "861458E2-6F71-40A1-AEAE-4C8292F01DE2",
        "availabilityError" : "runtime profile not found"
      },
      {
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "iPad Air (3rd generation)",
        "udid" : "0B495196-EC06-4DF2-82BA-6EEBF029E9E0",
        "availabilityError" : "runtime profile not found"
      }
    ]
  }
}
```

**Comment by mmcc007** [comment] 2019-11-24 00:26
I confirmed the output of `xcrun simctl list devices --json` is as expected.

Looks like the problem is that the emulators/simulators you have currently installed on your computer do not match what is found in the config file.
In your config file, you have 'Nexus 6P' and 'iPhone XS Max'. The guide shows they are not installed on your computer. 
You will either have to install the missing emulators/simulators or change your config file to match what is installed.

Let me know if this helps.

**Comment by mmcc007** [comment] 2019-11-24 02:39
Merged some improved messaging. If you still have an issue with this please re-open

**Comment by Xgamefactory** [comment] 2019-11-26 20:47
so this plugin only work with emulator not real device ?

**Comment by mmcc007** [comment] 2019-11-26 20:52
Works with real devices too.

**Comment by Xgamefactory** [comment] 2019-11-26 20:56
as i mentioned before my real device iphone xs max was connected when i get this errors.

**Comment by mmcc007** [comment] 2019-11-26 20:59
Is there an error message?

**Comment by mmcc007** [comment] 2019-11-26 21:02
To run on the real `SM G965F` device, the device has to be included in the config file

**Comment by Xgamefactory** [comment] 2019-11-28 10:21
device is included in config file

devices:
  ios:
    iPhone XS Max:

and connected
but getting error

**Comment by mmcc007** [comment] 2019-11-29 18:01
The output of screenshots, the guide, seems consistent.

The example app's screenshots.yaml is configured to run on 3 devices/emulators. screenshots will search for these 3 devices/emulators in your environment before starting. 
According to the guide, it is finding one emulator (`iPad Pro (12.9-inch) (2nd generation)`). It is not finding the others. 

According to the output of `xcrun simctl list devices` there is no `iPhone XS Max` simulator  installed (note: there is a `iPhone Xs Max`, but this is not a match). To run screenshots on the example, try installing the `iPhone XS Max` simulator.

It is finding a `SM G965F` real device which is probably a [Samsung](https://www.samsung.com/uk/support/model/SM-G965FZBABTU/) device.

Output of `flutter emulators`, probably does not include the `Nexus 6P` emulator. Try installing a `Nexus 6P` emulator.

So, to run on the example, you could try installing the `iPhone XS Max` simulator and the  `Nexus 6P` emulator (or change the screenshots.yaml).

If there is a problem running on a real `iPhone XS Max` device please provide the output of `ios-deploy -c`.

**Comment by mmcc007** [comment] 2020-01-16 07:26
No response, so closing for now.

**Closed by mmcc007** 2020-01-16 07:26 UTC
Labels: question
